#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
rm -rf .build
mkdir -p dist
mkdir -p .build

echo "from src to .build ... "
npx lsc -cp --no-header src/index.ls > .build/index.js
cp src/meta.json .build/meta.json
cp src/topo.json .build/topo.json
echo "bundle .build/index.js -> dist/index.js ... "
npx browserify -s pdmap-world .build/index.js > dist/index.js
rm -rf .build
echo "minify dist/index.js -> dist/index.min.js ..."
npx uglifyjs dist/index.js > dist/index.min.js

echo "copy dist to web ..."
rm -rf web/static/assets/lib/pdmap-world/dev/
mkdir -p web/static/assets/lib/pdmap-world/dev/
cp -R dist/* web/static/assets/lib/pdmap-world/dev/
